# Generated by Django 5.1 on 2024-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=6)),
                ('conf_pass', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
