# Generated by Django 5.1 on 2024-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
