# Generated by Django 5.1 on 2024-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0002_sign_up_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
