# Generated by Django 5.1 on 2024-12-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0004_sign_up_account_no_sign_up_contact_sign_up_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(default='', max_length=50)),
                ('rate', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
