# Generated by Django 5.1.6 on 2025-02-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0006_alter_loan_type_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(default='', max_length=30)),
                ('amount', models.PositiveIntegerField(default='', max_length=30)),
                ('year', models.PositiveIntegerField(default='', max_length=10)),
                ('rate', models.FloatField(default='')),
                ('total_amt', models.PositiveBigIntegerField(default='', max_length=30)),
            ],
        ),
    ]
