# Generated by Django 5.1.6 on 2025-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0011_loan_detail_account_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_emi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMI', models.FloatField(default='')),
                ('p_amt', models.FloatField(default='')),
                ('interest', models.FloatField(default='')),
                ('balance', models.FloatField(default='')),
                ('account_no', models.FloatField(default='')),
            ],
        ),
    ]
