# Generated by Django 5.1.6 on 2025-03-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0012_loan_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_emi',
            name='l_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
