# Generated by Django 5.1.6 on 2025-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0013_loan_emi_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_emi',
            name='EMI',
            field=models.PositiveBigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='account_no',
            field=models.PositiveBigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='balance',
            field=models.PositiveBigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='interest',
            field=models.PositiveBigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='l_name',
            field=models.PositiveBigIntegerField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='p_amt',
            field=models.PositiveBigIntegerField(default=''),
        ),
    ]
