# Generated by Django 5.1.6 on 2025-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0014_alter_loan_emi_emi_alter_loan_emi_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_emi',
            name='l_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
