# Generated by Django 5.1.6 on 2025-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0015_alter_loan_emi_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_emi',
            name='emi_id',
            field=models.PositiveBigIntegerField(default=''),
        ),
    ]
