# Generated by Django 5.1.6 on 2025-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0018_alter_loan_emi_emi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_emi',
            name='EMI',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='account_no',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='interest',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan_emi',
            name='p_amt',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
