# Generated by Django 5.1.6 on 2025-03-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0019_alter_loan_emi_emi_alter_loan_emi_account_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_emi',
            name='emi_id',
        ),
    ]
