# Generated by Django 5.1.6 on 2025-03-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0022_alter_loan_emi_emi_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loan_emi',
        ),
    ]
