# Generated by Django 5.1.6 on 2025-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0023_delete_loan_emi'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_emi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_id', models.PositiveBigIntegerField(blank=True, max_length=10, null=True)),
                ('EMI', models.PositiveBigIntegerField(default=0)),
                ('p_amt', models.PositiveBigIntegerField(default=0)),
                ('interest', models.PositiveBigIntegerField(default=0)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('account_no', models.PositiveBigIntegerField(default=0)),
                ('l_name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
