# Generated by Django 5.1.6 on 2025-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0024_loan_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_emi',
            name='emi_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
