# Generated by Django 5.1.6 on 2025-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0025_alter_loan_emi_emi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_emi',
            name='emi_id',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
