# Generated by Django 5.1 on 2024-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0003_alter_sign_up_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='account_no',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
