# Generated by Django 5.1.6 on 2025-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0005_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_type',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
