# Generated by Django 5.1.6 on 2025-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0008_emi_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi_detail',
            name='year',
            field=models.FloatField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan_detail',
            name='year',
            field=models.FloatField(default='', max_length=10),
        ),
    ]
