# Generated by Django 5.1.6 on 2025-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0009_alter_emi_detail_year_alter_loan_detail_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emi_detail',
        ),
        migrations.AddField(
            model_name='loan_detail',
            name='emi',
            field=models.FloatField(default=0),
        ),
    ]
