# Generated by Django 5.1.6 on 2025-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksystem', '0010_delete_emi_detail_loan_detail_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_detail',
            name='account_no',
            field=models.CharField(default='', max_length=16),
        ),
    ]
